import os
from colorama import init
init()
from colorama import Back,Style,Fore
from time import sleep

print(Fore.GREEN)
print("Developers " + "| "+ Fore.RED + "Yarous: " + Fore.BLUE + "GitHub|https://www.GitHub.com/Yarous " + Fore.YELLOW + "VK|https://vk.com/id464488877")
sleep(1)
print("Hy my name is Yaroslav my language is RU And i Developer the project!")
print(Fore.RED)
sleep(1)
print("MANUAL!")
print(Fore.BLUE)
sleep(1)
print("1|About!")
print(Fore.GREEN)
sleep(1)
print("2|Project and Folders!")
print(Fore.YELLOW)
sleep(1)
print("3|How to use i't!")
print(Fore.GREEN)
sleep(1)
print("4|Exit|ctrl + english C")

print(Fore.GREEN)
print("1|About!")
sleep(1)
print("Hy!My name is Yaroslav and my language is RU!I developer the project!This project connecting my python scripts to you " + Fore.BLUE + "DISCORD" + Fore.GREEN + " BOT!Project name|DSServer!")

sleep(3)
os.system('cls')

sleep(1)
print(Fore.BLUE)
print("2|Project and Folders!")
sleep(1)
os.system('cls')
print("File| Tkinter.py this UI for project!")
print("All Files: My SCRIPTS!")
sleep(1)
os.system('cls')
print(Fore.YELLOW)
sleep(1)
print("3|How to use i't!")
sleep(1)
os.system('cls')

sleep(1)
print("Enter this command|python Tkinter.py|In the window Enter bot TOKEN and ID if you don't have a bot create it here|https://discordapp.com/developers|Done!You bot Connectid!")

sleep(3)
print(Fore.RED)
print("BY")
os.system('cls')